### ISSUE TITLE
Can't save "This bot acts as a client"

### ISSUE THREAD

**Issue by ghost** [LiveHelperChat/telegram#36]
Hi

I can't save "This bot acts as a client". It goes straight to "We’ll be back soon!".

**Comment by gituser** [comment]
Hey @remdex!

Trying to set-up telegram plugin, followed documentation and everything and getting this error as well when trying to set-up bot to 'act as a client'.

Here is an error I'm getting:

```
Mar 30 19:22:57 [Warning] [default] [default] TypeError Object
(
    [message:protected] => count(): Argument #1 ($value) must be of type Countable|array, null given
    [string:Error:private] => TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/chat.domain.com/lhc_web/cache/compiledtemplates/e55fd0c6d7a5203c2b1fe216fa4741b6.php:2
Stack trace:
#0 /var/www/chat.domain.com/lhc_web/lib/core/lhcore/lhmodule.php(108): include()
#1 /var/www/chat.domain.com/lhc_web/lib/core/lhcore/lhmodule.php(658): erLhcoreClassModule::runModule()
#2 /var/www/chat.domain.com/lhc_web/index.php(50): erLhcoreClassModule::moduleInit()
#3 {main}
    [code:protected] => 0
    [file:protected] => /var/www/chat.domain.com/lhc_web/cache/compiledtemplates/e55fd0c6d7a5203c2b1fe216fa4741b6.php
    [line:protected] => 2
    [trace:Error:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/chat.domain.com/lhc_web/lib/core/lhcore/lhmodule.php
                    [line] => 108
                    [function] => include
                )

            [1] => Array
                (
                    [file] => /var/www/chat.domain.com/lhc_web/lib/core/lhcore/lhmodule.php
                    [line] => 658
                    [function] => runModule
                    [class] => erLhcoreClassModule
                    [type] => ::
                )

            [2] => Array
                (
                    [file] => /var/www/chat.domain.com/lhc_web/index.php
                    [line] => 50
                    [function] => moduleInit
                    [class] => erLhcoreClassModule
                    [type] => ::
                )

        )

    [previous:Error:private] => 
)
```
Most likely something to do with departments setting as it's passed as an array 'dep[]'.
Environment is PHP 8.0. I did `composer update` in the `extension/lhctelegram` but still no luck, maybe you could take a look?


For now I did a workaround by changing the value inside the database via:
```
update lhc_telegram_bot set bot_client=1 where id=1
```
Thank you.

**Comment by remdex** [comment]
I'll check that next week
